services:
  postgres:
    image: postgres:latest
    container_name: beside_mom
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: besidemom
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_for_besidemom
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    depends_on:
      - postgres

  server:
    container_name: beside_mom_server
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment: 
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - JWT_SECRET=${JWT_SECRET}
    restart: on-failure